services:

  react:
    image: node:22-slim
    container_name: react
    ports:
      - "127.0.0.1:2000:2000"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=development
      - PORT=2000
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  nestjs:
    image: node:22-slim
    container_name: nestjs
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./back:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"