version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestchat
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestchat
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
