version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chat
      - JWT_SECRET=your-secret-key
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 